name: Stage

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: stage
  cancel-in-progress: false

jobs:
  build:
    if: ${{ github.repository_owner == 'siyuan-note' }}
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}
      QINIU_BUCKET: ${{ secrets.QINIU_BUCKET }}
      QINIU_AK: ${{ secrets.QINIU_AK }}
      QINIU_SK: ${{ secrets.QINIU_SK }}
      RHYTHEM_TOKEN: ${{ secrets.RHYTHEM_TOKEN }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      - name: Go staging
        run: go run ./actions/stage
      - name: Commit and push
        run: |-
          git config --global user.email "bot@github.com" && git config --global user.name "Bot"
          git diff
          git add . && git commit -m ":bookmark: Staging" || exit 0
          git pull --rebase
          git push
      - name: Index bazaar
        run: go run ./actions/index
      - name: Go hashing
        run: go run ./actions/hash
